# Generated by Django 3.2.12 on 2022-02-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='price',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgroup',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MetaGroup',
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categroria', to='sales_backend.productgroup'),
        ),
    ]
