# Generated by Django 2.2.16 on 2022-04-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
