# Generated by Django 2.2.16 on 2022-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0005_auto_20220424_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
