# Generated by Django 2.2.16 on 2022-04-24 15:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220315_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='group',
            field=models.TextField(default=django.contrib.auth.models.Group),
        ),
    ]
