# Generated by Django 2.2.16 on 2022-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
